const pptxgen = require('pptxgenjs');
const fs = require('fs');
const path = require('path');

const root = __dirname;
const out = path.join(root, 'Manual-de-Uso-Academia-Agile.pptx');
const logo = path.join(root, 'assets', 'favicon.png');
const pptx = new pptxgen();
pptx.layout = 'LAYOUT_WIDE';
pptx.author = 'Guilherme Alisson Natalino da Silva';
pptx.subject = 'Manual de uso da Academia Agile';
pptx.title = 'Manual de Uso - Academia Agile';
pptx.company = 'Academia Agile';
pptx.lang = 'pt-BR';
pptx.theme = { headFontFace: 'Aptos Display', bodyFontFace: 'Aptos', lang: 'pt-BR' };
pptx.defineSlideMaster({
  title: 'MASTER',
  background: { color: '0B1020' },
  objects: [
    { line: { x: 0.45, y: 0.88, w: 12.4, h: 0, line: { color: '1B2234', width: 1 } } },
    { text: { text: 'ACADEMIA AGILE', options: { x: 1.02, y: 0.31, w: 2.8, h: 0.2, fontFace: 'Aptos', fontSize: 10, bold: true, color: 'F5F7FC', margin: 0 } } },
  ],
  slideNumber: { x: 12.45, y: 7.05, color: 'A6B1CD', fontFace: 'Aptos', fontSize: 9 }
});

const C = { bg:'0B1020', surface:'141925', surface2:'1B2234', blue:'5B82FF', green:'23D56E', violet:'A77BFF', white:'F5F7FC', muted:'A6B1CD', red:'FF8080', amber:'FFBE50' };
const W = 13.333, H = 7.5;
function addHeader(slide, section) {
  if (fs.existsSync(logo)) slide.addImage({ path: logo, x: 0.45, y: 0.28, h: 0.46 });
  slide.addText(section.toUpperCase(), { x: 10.2, y: 0.34, w: 2.25, h: 0.18, fontSize: 8, bold: true, color: C.muted, align: 'right', margin: 0, charSpacing: 1 });
}
function addSlide(section) { const s = pptx.addSlide('MASTER'); addHeader(s, section); return s; }
function title(s, heading, sub) { s.addText(heading, { x: 0.65, y: 1.2, w: 11.9, h: 0.5, fontSize: 28, bold: true, color: C.white, margin: 0, breakLine: false }); if (sub) s.addText(sub, { x: 0.68, y: 1.82, w: 11.5, h: 0.34, fontSize: 12, color: C.muted, margin: 0 }); }
function box(s, x, y, w, h, fill=C.surface, line=C.surface2, radius=0.12) { s.addShape(pptx.ShapeType.roundRect, { x, y, w, h, rectRadius: radius, fill: { color: fill }, line: { color: line, width: 1 } }); }
function card(s, x, y, w, h, head, body, accent, icon) { box(s,x,y,w,h); s.addShape(pptx.ShapeType.rect,{x,y,w:0.055,h,fill:{color:accent},line:{color:accent}}); s.addText(icon || '',{x:x+0.28,y:y+0.2,w:0.4,h:0.25,fontSize:16,bold:true,color:accent,margin:0}); s.addText(head,{x:x+0.78,y:y+0.22,w:w-1.05,h:0.25,fontSize:14,bold:true,color:C.white,margin:0}); s.addText(body,{x:x+0.28,y:y+0.72,w:w-0.55,h:h-0.9,fontSize:10.5,color:C.muted,breakLine:false,margin:0.02,fit:'shrink'}); }
function bullets(s, items, x, y, w, accent=C.blue) { items.forEach((item,i)=>{const yy=y+i*0.55; s.addShape(pptx.ShapeType.ellipse,{x,y:yy+0.12,w:0.1,h:0.1,fill:{color:accent},line:{color:accent}}); s.addText(item,{x:x+0.22,y:yy,w:w-0.22,h:0.35,fontSize:15,color:C.white,margin:0,fit:'shrink'});}); }
function label(s, t, x, y, w, color=C.muted) { s.addText(t,{x,y,w,h:0.2,fontSize:9,bold:true,color,margin:0,charSpacing:1}); }

// 1
let s=pptx.addSlide(); s.background={color:C.bg}; s.addShape(pptx.ShapeType.rect,{x:0,y:0,w:0.18,h:H,fill:{color:C.blue},line:{color:C.blue}}); if(fs.existsSync(logo))s.addImage({path:logo,x:0.75,y:1.05,h:1.05}); s.addText('Academia Agile',{x:0.78,y:2.35,w:8.8,h:0.6,fontSize:38,bold:true,color:C.white,margin:0}); s.addText('Manual completo de uso',{x:0.82,y:3.12,w:8,h:0.4,fontSize:23,bold:true,color:C.blue,margin:0}); s.addText('Aprenda, pratique, acompanhe sua evolução e peça ajuda quando precisar.',{x:0.84,y:3.82,w:7.8,h:0.65,fontSize:16,color:C.muted,margin:0,fit:'shrink'}); box(s,9,1.15,3.25,4.75); label(s,'JORNADA',9.45,1.65,2); [['Estudos',C.blue],['Métricas',C.violet],['Conquistas',C.green],['FAC + SAC',C.amber]].forEach(([t,c],i)=>{const y=2.15+i*.72;s.addShape(pptx.ShapeType.ellipse,{x:9.45,y,w:.18,h:.18,fill:{color:c},line:{color:c}});s.addText(t,{x:9.82,y:y-0.02,w:1.9,h:.25,fontSize:14,bold:true,color:C.white,margin:0});}); s.addText('Versão 1.0 · Setembro de 2026',{x:.85,y:6.55,w:4.5,h:.2,fontSize:10,color:C.muted,margin:0});
// 2
s=addSlide('Visão geral');title(s,'O que você encontra na plataforma','A Academia Agile organiza sua prática em um fluxo simples e progressivo.');[['Jornada','Veja seu nível atual, a próxima meta e o caminho de evolução.',C.blue,'01'],['Estudos','Acesse vídeos e pratique perguntas por assunto.',C.violet,'02'],['Métricas','Acompanhe domínio, precisão e pontos de atenção.',C.green,'03'],['Ajuda','Consulte a FAC antes de abrir um chamado no SAC.',C.amber,'04']].forEach((v,i)=>card(s,.7+i*3.08,2.65,2.8,2,v[0],v[1],v[2],v[3]));s.addText('A navegação principal fica no topo. No celular, os mesmos destinos aparecem em uma barra adaptada.',{x:.72,y:5.2,w:11.7,h:.4,fontSize:14,color:C.muted,margin:0});
// 3
s=addSlide('Primeiro acesso');title(s,'Comece sem complicação','Você pode explorar a plataforma antes de criar uma conta.');bullets(s,['Abra a página da Academia Agile.','Use a Jornada, Estudos e Métricas para conhecer a interface.','O progresso de visitante fica somente na sessão atual.','Para sincronizar entre dispositivos, crie uma conta ou entre em uma existente.'],.9,2.5,6.2);box(s,7.6,2.35,4.3,2.7);label(s,'VISITANTE',8,2.75,2);s.addText('0% domínio',{x:8,y:3.25,w:3.2,h:.4,fontSize:24,bold:true,color:C.white,margin:0});s.addShape(pptx.ShapeType.rect,{x:8,y:4.05,w:3.3,h:.1,fill:{color:C.surface2},line:{color:C.surface2}});s.addText('Sem dados de outra pessoa',{x:8,y:4.45,w:3.2,h:.25,fontSize:11,color:C.green,margin:0});
// 4
s=addSlide('Conta');title(s,'Criar conta ou entrar','A conta permite salvar seu progresso com segurança na nuvem.');card(s,.8,2.35,3.8,2.5,'Criar conta','Informe nome, sobrenome, email, unidade e uma senha de 8 a 128 caracteres.',C.blue,'A');card(s,4.8,2.35,3.8,2.5,'Maioridade','O cadastro é destinado exclusivamente a pessoas com 18 anos ou mais. Marque a confirmação.',C.violet,'B');card(s,8.8,2.35,3.8,2.5,'Consentimentos','Leia a Política de Privacidade e os Termos de Uso. Analytics é opcional e separado.',C.green,'C');s.addText('Para recuperar uma senha, use “Esqueci minha senha” no formulário de login e confira seu email.',{x:.85,y:5.55,w:11.2,h:.35,fontSize:14,color:C.muted,margin:0});
// 5
s=addSlide('Privacidade');title(s,'Consentimentos e dados','As escolhas de privacidade ficam separadas do uso educacional principal.');card(s,.8,2.45,3.8,2.2,'Obrigatório','Aceite da Política de Privacidade e dos Termos de Uso para criar a conta.',C.blue,'✓');card(s,4.8,2.45,3.8,2.2,'Obrigatório','Confirmação de maioridade: a plataforma é exclusiva para maiores de 18 anos.',C.violet,'18');card(s,8.8,2.45,3.8,2.2,'Opcional','Analytics mede uso da plataforma para orientar melhorias. Recusar não bloqueia os estudos.',C.green,'⌁');s.addText('Você pode alterar a preferência de Analytics no menu da conta. Solicitações de privacidade: acaeacademiaagile@gmail.com.',{x:.85,y:5.3,w:11.5,h:.5,fontSize:13,color:C.muted,margin:0,fit:'shrink'});
// 6
s=addSlide('Estudos');title(s,'Estude por assunto','Cada card reúne o material e a prática daquele conceito.');box(s,.8,2.35,5.4,3.25);s.addText('Sprint Goal',{x:1.15,y:2.72,w:3.5,h:.3,fontSize:20,bold:true,color:C.white,margin:0});s.addText('Scrum · 0/1 respondidas · 0% domínio',{x:1.15,y:3.22,w:4.3,h:.25,fontSize:11,color:C.muted,margin:0});box(s,1.15,4,1,.42,C.surface2,C.surface2);s.addText('Vídeo',{x:1.35,y:4.1,w:.7,h:.2,fontSize:11,bold:true,color:C.white,margin:0});box(s,2.35,4,1.2,.42,C.blue,C.blue);s.addText('Praticar',{x:2.55,y:4.1,w:.85,h:.2,fontSize:11,bold:true,color:C.white,margin:0});s.addText('O botão Praticar aparece somente depois que houver atividade registrada naquele assunto.',{x:1.15,y:4.8,w:4.3,h:.5,fontSize:11,color:C.green,margin:0,fit:'shrink'});bullets(s,['Use o vídeo para revisar o conceito.','Leia o contador no formato respondidas/total.','Depois da primeira resposta, pratique novamente quando quiser.'],6.9,2.55,5.3,C.violet);
// 7
s=addSlide('Prática');title(s,'Responda às perguntas','A ordem das alternativas é embaralhada para reduzir respostas por posição.');box(s,.8,2.35,11.7,.7);s.addText('Treinamento',{x:1.1,y:2.56,w:1.5,h:.2,fontSize:11,bold:true,color:C.blue,margin:0});s.addText('Intermediário',{x:2.65,y:2.56,w:1.8,h:.2,fontSize:11,bold:true,color:C.violet,margin:0});s.addText('5/12',{x:11.55,y:2.56,w:.55,h:.2,fontSize:11,color:C.muted,align:'right',margin:0});s.addText('Leia o enunciado e escolha uma alternativa.',{x:1,y:3.55,w:7.6,h:.35,fontSize:20,bold:true,color:C.white,margin:0});['Alternativa A','Alternativa B','Alternativa C','Alternativa D'].forEach((t,i)=>{const y=4.2+i*.55;box(s,1,y,10.7,.42);s.addText(String.fromCharCode(65+i),{x:1.23,y:y+.12,w:.12,h:.12,fontSize:8,bold:true,color:C.blue,align:'center',margin:0});s.addText(t,{x:1.62,y:y+.1,w:4,h:.2,fontSize:12,color:C.white,margin:0});});
// 8
s=addSlide('Métricas');title(s,'Entenda seus indicadores','Os números mostram o que já foi respondido, não um progresso inventado.');card(s,.8,2.35,3.75,1.8,'Domínio médio','Considera somente competências que já possuem respostas.',C.blue,'📊');card(s,4.8,2.35,3.75,1.8,'Precisão','Acertos gerais em todas as perguntas respondidas.',C.violet,'🎯');card(s,8.8,2.35,3.75,1.8,'Pontos de atenção','Lista todas as competências abaixo de 70%.',C.green,'!');s.addText('Exemplo de leitura:',{x:.85,y:4.75,w:2,h:.25,fontSize:14,bold:true,color:C.muted,margin:0});s.addText('50% · 2/4',{x:2.7,y:4.63,w:2,h:.4,fontSize:23,bold:true,color:C.white,margin:0});s.addText('Você acertou 2 de 4 respostas naquele grupo.',{x:4.7,y:4.75,w:5.8,h:.25,fontSize:14,color:C.muted,margin:0});
// 9
s=addSlide('Conquistas');title(s,'Evolua com conquistas','As conquistas reconhecem constância, desempenho e exploração dos conteúdos.');[['Primeiro passo','1ª pergunta',C.blue],['Maratona','25 respostas',C.violet],['Constância','7 dias seguidos',C.green],['Sessão perfeita','100% de acertos',C.amber]].forEach((v,i)=>{const x=.85+(i%2)*6,y=2.45+Math.floor(i/2)*1.25;box(s,x,y,5.35,.9);s.addShape(pptx.ShapeType.ellipse,{x:x+.25,y:y+.22,w:.45,h:.45,fill:{color:v[2]},line:{color:v[2]}});s.addText(v[0],{x:x+.95,y:y+.18,w:3,h:.25,fontSize:15,bold:true,color:C.white,margin:0});s.addText(v[1],{x:x+.95,y:y+.5,w:3.5,h:.2,fontSize:11,color:C.muted,margin:0});});s.addText('Veja as conquistas desbloqueadas e bloqueadas na tela Perfil.',{x:.9,y:5.5,w:8.5,h:.3,fontSize:14,color:C.muted,margin:0});
// 10
s=addSlide('Ajuda');title(s,'Consulte a FAC antes do SAC','A FAC resolve as dúvidas mais comuns sem precisar abrir um chamado.');box(s,.8,2.35,5.4,3.2);s.addText('FAC · Perguntas frequentes',{x:1.15,y:2.72,w:4.3,h:.3,fontSize:17,bold:true,color:C.white,margin:0});['Como salvo meu progresso?','Como recupero minha senha?','O que o Analytics coleta?','Como excluo minha conta?'].forEach((q,i)=>s.addText('›  '+q,{x:1.15,y:3.35+i*.43,w:4.5,h:.22,fontSize:12,color:C.muted,margin:0}));box(s,6.8,2.35,5.4,3.2);s.addText('SAC · Abrir chamado',{x:7.15,y:2.72,w:4.3,h:.3,fontSize:17,bold:true,color:C.white,margin:0});bullets(s,['Entre na sua conta.','Escolha uma categoria.','Explique o problema com detalhes.','Acompanhe seus chamados recentes.'],7.15,3.35,4.5,C.green);
// 11
s=addSlide('Conta');title(s,'Gerencie sua conta','O menu de conta reúne privacidade, sessão e exclusão dos dados.');card(s,.8,2.35,3.75,2.15,'Analytics de uso','Mostra quais telas e recursos são usados para orientar melhorias. Não é necessário para estudar.',C.blue,'⌁');card(s,4.8,2.35,3.75,2.15,'Excluir conta','Remove a conta e os dados associados. A ação é confirmada antes de ser executada.',C.red,'⌫');card(s,8.8,2.35,3.75,2.15,'Sair da conta','Encerra a sessão no dispositivo atual. O progresso continua na nuvem.',C.violet,'↪');s.addText('A política de privacidade está disponível no cadastro e em data-policy.html.',{x:.85,y:5.35,w:8.8,h:.3,fontSize:14,color:C.muted,margin:0});
// 12
s=addSlide('Solução de problemas');title(s,'Quando algo não sair como esperado','Use este checklist antes de abrir um chamado.');bullets(s,['Atualize a página com Ctrl + F5 para remover cache antigo.','Confirme se você está na conta correta.','Verifique se o botão Praticar aparece apenas após uma resposta.','Confira se o email de recuperação chegou ao spam.','Se o problema continuar, abra o SAC com categoria e detalhes.'],.9,2.4,7.2,C.blue);box(s,8.7,2.55,3.5,2.5);label(s,'CANAL OFICIAL',9.1,2.95,2.5);s.addText('acaeacademiaagile@gmail.com',{x:9.1,y:3.45,w:2.7,h:.5,fontSize:15,bold:true,color:C.white,margin:0,fit:'shrink'});s.addText('Use o SAC para problemas técnicos e a política para solicitações de privacidade.',{x:9.1,y:4.25,w:2.7,h:.5,fontSize:11,color:C.muted,margin:0,fit:'shrink'});
// 13
s=addSlide('Resumo');title(s,'Seu caminho na Academia Agile','Explore, pratique, acompanhe e peça ajuda quando precisar.');[['Explore','Conheça a Jornada e os Estudos.',C.blue,'1'],['Pratique','Responda e revise seus conceitos.',C.violet,'2'],['Acompanhe','Leia suas métricas e conquistas.',C.green,'3'],['Resolva','Consulte a FAC e use o SAC.',C.amber,'4']].forEach((v,i)=>{const x=.8+i*3.05;box(s,x,2.6,2.55,2.15);s.addText(v[3],{x:x+.25,y:2.9,w:.45,h:.4,fontSize:24,bold:true,color:v[2],margin:0});s.addText(v[0],{x:x+.85,y:2.95,w:1.4,h:.25,fontSize:16,bold:true,color:C.white,margin:0});s.addText(v[1],{x:x+.25,y:3.7,w:2,h:.5,fontSize:11,color:C.muted,margin:0});});s.addText('Site: https://aeca-agile-excellence.web.app',{x:.85,y:5.65,w:7,h:.25,fontSize:14,bold:true,color:C.blue,margin:0});s.addText('Obrigado por fazer parte da jornada.',{x:.85,y:6.2,w:6.5,h:.25,fontSize:14,color:C.muted,margin:0});

pptx.writeFile({ fileName: out });
